apps/pages/urls.py
from django.urls import path
from .views import IndexView, ContactView

app_name = 'pages'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contact/', ContactView.as_view(), name='contact'),
]

apps/shop/urls.py
from django.urls import path
from .views import ShopView, ProductView, CartView, create_product, create_review, get_reviews, add_to_cart, remove_from_cart, create_checkout_session, CartSuccessView, stripe_webhook

app_name = 'shop'

urlpatterns = [
    path('shop/', ShopView.as_view(), name='products'),
    path('product/create/', create_product, name='create_product'),
    path('product/review/<str:slug>/', create_review, name='create_review'),
    path('product/reviews/<str:slug>/', get_reviews, name='get_reviews'),
    path('product/<str:slug>/', ProductView.as_view(), name='product'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/success/', CartSuccessView.as_view(), name='cart_success'),

    path('add-to-cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('create-checkout-session/', create_checkout_session, name='create_checkout_session'),
    path('webhook-stripe/', stripe_webhook, name='stripe_webhook'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.pages.urls')),
    path('', include('apps.shop.urls')),
    path('accounts/', include('apps.accounts.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

templates/includes/footer.html
{% load static %}
<footer class="footer-two section-bg position-relative z-index-1 overflow-hidden">

    <img src="{% static 'assets/images/gradients/footer-gradient-bg.png' %}" alt="" class="bg--gradient">

    <img src="{% static 'assets/images/shapes/footer-pattern1.png' %}" alt=""
        class="position-absolute end-0 top-0 z-index--1">
    <img src="{% static 'assets/images/shapes/footer-pattern2.png' %}" alt=""
        class="position-absolute start-0 top-0 z-index--1">

    <div class="footer-inner padding-y-120">
        <div class="container container-two">
            <div class="row gy-5">
                <div class="col-xl-3 col-sm-6">
                    <div class="footer-widget">
                        <div class="footer-widget__logo">
                            <a href="index.html">
                                <img src="{% static 'assets/images/logo/logo.png' %}" alt="" class="white-version">
                                <img src="{% static 'assets/images/logo.png' %}" alt=""
                                    class="dark-version" style="width: 150px; height: 250px; object-fit: cover;">
                            </a>
                        </div>
                        <p class="footer-widget__desc">Vyvo. Tienda virtual que ofrece productos de calidad a precios accesibles.</p>
                        <div class="footer-widget__social">
                            <ul class="social-icon-list">
                                <li class="social-icon-list__item">
                                    <a href="https://www.facebook.com" class="social-icon-list__link flx-center"><i
                                            class="fab fa-facebook-f"></i></a>
                                </li>
                                <li class="social-icon-list__item">
                                    <a href="https://www.twitter.com" class="social-icon-list__link flx-center"> <i
                                            class="fab fa-twitter"></i></a>
                                </li>
                                <li class="social-icon-list__item">
                                    <a href="https://www.linkedin.com" class="social-icon-list__link flx-center"> <i
                                            class="fab fa-linkedin-in"></i></a>
                                </li>
                                <li class="social-icon-list__item">
                                    <a href="https://www.pinterest.com" class="social-icon-list__link flx-center">
                                        <i class="fab fa-pinterest-p"></i></a>
                                </li>
                                <li class="social-icon-list__item">
                                    <a href="https://www.pinterest.com" class="social-icon-list__link flx-center">
                                        <i class="fab fa-youtube"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 col-sm-6 col-xs-6">
                    <div class="footer-widget">
                        <h5 class="footer-widget__title">Tienda</h5>
                        <ul class="footer-lists">
                            <li class="footer-lists__item"><a href="{% url 'shop:products' %}"
                                    class="footer-lists__link">Productos </a></li>
                            <li class="footer-lists__item"><a href="javascript:void(0)"
                                    class="footer-lists__link">Categorias</a></li>
                            <li class="footer-lists__item"><a href="javascript:void(0)"
                                    class="footer-lists__link">Carrito</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-1 d-xl-block d-none"></div>
                <div class="col-xl-3 col-sm-6 col-xs-6">
                    <div class="footer-widget">
                        <h5 class="footer-widget__title">Blog </h5>
                        <ul class="footer-lists">
                            <li class="footer-lists__item"><a href="javascript:void(0)"
                                    class="footer-lists__link">Blog </a></li>
                            <li class="footer-lists__item"><a href="javascript:void(0)"
                                    class="footer-lists__link">Populares</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 col-xs-6">
                    <div class="footer-widget">
                        <h5 class="footer-widget__title">Categorias</h5>
                        <ul class="footer-lists">
                            {% for category in categories_footer %}
                            <li class="footer-lists__item"><a href="{% url 'shop:products' %}?category={{ category.id }}"
                                    class="footer-lists__link">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom-footer-two">
        <div class="container container-two">
            <div class="bottom-footer__inner flx-between gap-3">
                <p class="bottom-footer__text font-14"> Copyright &copy; 2025 Vyvo, All rights reserved.</p>
            </div>
        </div>
    </div>
</footer>

templates/includes/header.html
{% load static %}
<header class="header">
    <div class="container container-full">
        <nav class="header-inner flx-between">
            <div class="logo">
                <a href="{% url 'pages:index' %}" class="link white-version">
                    <img src="{% static 'assets/images/logo/logo.png' %}" alt="Logo">
                </a>
                <a href="{% url 'pages:index' %}" class="link dark-version">
                    <img src="{% static 'assets/images/logo.png' %}" style="height: 100px; width: 150px; object-fit: cover;" alt="Logo">
                </a>
            </div>

            <div class="header-menu d-lg-block d-none">

                <ul class="nav-menu flx-align ">
                    <li class="nav-menu__item">
                        <a href="{% url 'pages:index' %}" class="nav-menu__link">Inicio</a>
                    </li>
                    <li class="nav-menu__item">
                        <a href="{% url 'shop:products' %}" class="nav-menu__link">Productos</a>
                    </li>
                    <li class="nav-menu__item">
                        <a href="javascript:void(0)" class="nav-menu__link">Categorias</a>
                    </li>
                    <li class="nav-menu__item">
                        <a href="javascript:void(0)" class="nav-menu__link">Blog</a>
                    </li>
                    <li class="nav-menu__item">
                        <a href="javascript:void(0)" class="nav-menu__link">Contacto</a>
                    </li>
                </ul>
            </div>

            <div class="header-right flx-align">
                <a href="{% url 'shop:cart' %}" class="header-right__button cart-btn position-relative">
                    <img src="{% static 'assets/images/icons/cart.svg' %}" alt="" class="white-version">
                    <img src="{% static 'assets/images/icons/cart-white.svg' %}" alt="" class="dark-version">
                </a>

                <div class="header-right__inner gap-3 flx-align d-lg-flex d-none">

                    <a href="{% if request.user.is_authenticated %}{% url 'profile' request.user.username %}{% else %}{% url 'account_signup' %}{% endif %}" class="btn btn-main pill">
                        <span class="icon-left icon">
                            <img src="{% static 'assets/images/icons/user.svg' %}" alt="">
                        </span>
                        {% if request.user.is_authenticated %}
                            {{ request.user.username }}
                        {% else %}
                            Crear cuenta
                        {% endif %}
                    </a>
                </div>
                <button type="button" class="toggle-mobileMenu d-lg-none"> <i class="las la-bars"></i> </button>
            </div>
        </nav>
    </div>
</header>

templates/includes/mobile-menu.html
{% load static %}
<div class="mobile-menu d-lg-none d-block">
    <button type="button" class="close-button"> <i class="las la-times"></i> </button>
    <div class="mobile-menu__inner">
        <a href="index.html" class="mobile-menu__logo">
            <img src="{% static 'assets/images/logo/logo.png' %}" alt="Logo" class="white-version">
            <img src="{% static 'assets/images/logo/white-logo-two.png' %}" alt="Logo" class="dark-version">
        </a>
        <div class="mobile-menu__menu">

            <ul class="nav-menu flx-align nav-menu--mobile">
                <li class="nav-menu__item">
                    <a href="{% url 'pages:index' %}" class="nav-menu__link">Inicio</a>
                </li>
                <li class="nav-menu__item">
                    <a href="{% url 'shop:products' %}" class="nav-menu__link">Productos</a>
                </li>
                <li class="nav-menu__item">
                    <a href="javascript:void(0)" class="nav-menu__link">Categorias</a>
                </li>
                <li class="nav-menu__item">
                    <a href="javascript:void(0)" class="nav-menu__link">Blog</a>
                </li>
                <li class="nav-menu__item">
                    <a href="{% url 'pages:contact' %}" class="nav-menu__link">Contacto</a>
                </li>
            </ul>
            <div class="header-right__inner d-lg-none my-3 gap-1 d-flex flx-align">

                <a href="register.html" class="btn btn-main pill">
                    <span class="icon-left icon">
                        <img src="{% static 'assets/images/icons/user.svg' %}" alt="">
                    </span>Create Account
                </a>
            </div>
        </div>
    </div>
</div>

templates/includes/product-card.html
<div class="col-xl-4 col-sm-6">
    <div class="product-item section-bg">
        <div class="product-item__thumb d-flex">
            <a href="{% url 'shop:product' product.slug %}" class="link w-100">
                <img style="height: 210px" src="{{ product.get_featured_image }}" alt=""
                    class="cover-img">
            </a>
        </div>
        <div class="product-item__content">
            <h6 class="product-item__title">
                <a href="{% url 'shop:product' product.slug %}" class="link">{{ product.name }}</a>
            </h6>
            <div class="product-item__info flx-between gap-2">
                <span class="product-item__author">
                    por
                    <a href="{% url 'profile' product.creator.username %}" class="link hover-text-decoration-underline">
                        {{ product.creator.username }}</a>
                </span>
                <div class="flx-align gap-2">
                    <h6 class="product-item__price mb-0">${{ product.price }}</h6>
                </div>
            </div>
            <div class="product-item__bottom flx-between gap-2">
                <div>
                    <div class="d-flex align-items-center gap-1">
                        <ul class="star-rating">
                            {{ product.fill_stars|safe }}
                        </ul>
                        <span class="star-rating__text text-heading fw-500 font-14">
                            ({{ product.get_favorites_count }})</span>
                    </div>
                </div>
                <a href="{% url 'shop:product' product.slug %}"
                    class="btn btn-outline-light btn-sm pill">Ver más</a>
            </div>
        </div>
    </div>
</div>